-- Migration: edit history for items and boards
-- Run this once in the Supabase SQL editor, after the earlier migrations.
-- Stores human-readable, one-line-per-change summaries (generated by the
-- app at save time — see item.html/board.html), not raw before/after data.
-- Only captures edits made through the admin tool itself.
--
-- "90 day history" is enforced as a rolling display window (the app only
-- queries changed_at >= now() - 90 days) rather than actual row deletion —
-- this is a low-volume text log, so there's no real need to prune it.

create table if not exists edit_history (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null check (entity_type in ('item', 'board')),
  entity_id uuid not null,
  summary text not null,
  changed_at timestamptz not null default now()
);

create index if not exists idx_edit_history_entity on edit_history(entity_type, entity_id, changed_at desc);

alter table edit_history enable row level security;

drop policy if exists "authenticated full access" on edit_history;
create policy "authenticated full access" on edit_history
  for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
